# Generated by Django 5.0.3 on 2024-04-23 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jurusan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kodejurusan', models.CharField(max_length=50, verbose_name='Kode Prodi')),
                ('namajurusan', models.CharField(max_length=150, verbose_name='Program studi')),
                ('jenjang', models.CharField(blank=True, max_length=150, null=True, verbose_name='jenjang')),
            ],
        ),
        migrations.CreateModel(
            name='mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(max_length=50, verbose_name='Nim')),
                ('nama', models.CharField(max_length=150, verbose_name='Nama Lengkap')),
                ('jk', models.CharField(choices=[('L', 'LAKI-LAKI'), ('P', 'PEREMPUAN')], max_length=50, verbose_name='Jenis Kelamin')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='E-Mail')),
                ('jurusan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perkuliahan.jurusan')),
            ],
        ),
    ]
