# Generated by Django 5.0.3 on 2024-06-19 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perkuliahan', '0002_matakuliah'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mahasiswa',
            old_name='nama',
            new_name='namalengkap',
        ),
        migrations.RenameField(
            model_name='matakuliah',
            old_name='manamk',
            new_name='namamk',
        ),
        migrations.AlterField(
            model_name='jurusan',
            name='jenjang',
            field=models.CharField(blank=True, choices=[('S1', 'STRATA 1'), ('S2', 'STRATA 2'), ('S3', 'STRATA 3'), ('D3', 'DIPLOMA 3'), ('D4', 'DIPLOMA 4')], max_length=150, null=True, verbose_name='jenjang'),
        ),
        migrations.CreateModel(
            name='Dosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nidn', models.CharField(max_length=20, verbose_name='Nidn')),
                ('namadosen', models.CharField(max_length=150, verbose_name='NamaLengkap')),
                ('gelar', models.CharField(help_text='S.Kom. ,M.Kom', max_length=30, verbose_name='Gelar')),
                ('tgllahir', models.DateField(blank=True, null=True, verbose_name='Tanggal Lahir')),
                ('templahir', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tempat Lahir')),
                ('foto', models.ImageField(upload_to='foto mhs', verbose_name='Foto')),
                ('cv', models.ImageField(upload_to='cv_dosen', verbose_name='CV')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jurusan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perkuliahan.jurusan', verbose_name='Program Studi')),
            ],
        ),
    ]
