# Generated by Django 5.0.3 on 2024-06-19 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perkuliahan', '0003_rename_nama_mahasiswa_namalengkap_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mahasiswa',
            old_name='namalengkap',
            new_name='namamahasiswa',
        ),
    ]
