# Generated by Django 5.0.3 on 2024-06-19 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perkuliahan', '0007_rename_namamahasiswa_mahasiswa_namamalengkap'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mahasiswa',
            old_name='namamalengkap',
            new_name='namalengkap',
        ),
    ]
