# Generated by Django 5.0.3 on 2024-06-19 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perkuliahan', '0008_rename_namamalengkap_mahasiswa_namalengkap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosen',
            name='jurusan',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='perkuliahan.jurusan', verbose_name='Program Studi'),
        ),
    ]
